// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfmroiyqrrhsxhwmgztr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbXJvaXlxcnJoc3hod21nenRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTE0MDUsImV4cCI6MjA2Mzc2NzQwNX0.wlI3hSdUAypBDYozp_7DFrtwF6Y-WVLiZcRo8aYa_Do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);